### ISSUE TITLE
who can help me!  3Q

### ISSUE THREAD

**Issue by otherChild** [adamw/elasticmq#108]
java -jar elasticmq-server-0.13.3.jar
20:28:36.589 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.3) ...
20:28:36.600 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticmq.server.Main$.main(Main.scala:18)
	at org.elasticmq.server.Main.main(Main.scala)

**Comment by adamw** [comment]
What's your `java -version`?

**Comment by otherChild** [comment]
@adamw 
java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by adamw** [comment]
Newer versions require Java 8, could you try with that?

**Comment by otherChild** [comment]
ok, I will try it.

**Comment by otherChild** [comment]
I upgrade java8 success.
but exec `java -version`
 still
java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by adamw** [comment]
Well that depends on your OS, setup, etc., I don't think I'll be able to help with upgrading java, sorry

**Comment by otherChild** [comment]
ok， thank you very!!!
