### ISSUE TITLE
`akka.http.scaladsl.model.ContentType$WithMissingCharset` on 0.13.7 with PHP AWS SDK

### ISSUE THREAD

**Issue by eXtreme** [adamw/elasticmq#115]
So, after upgrading to 0.13.7 (because of #114) my client based on latest PHP AWS SDK returns this error, when trying to receive messages:

```
     <ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
        <Error>
          <Type>Sender</Type>
          <Code>Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.
  http.scaladsl.model.ContentType$WithMissingCharset))</Code>
          <Message>Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class ak
  ka.http.scaladsl.model.ContentType$WithMissingCharset)); see the SQS docs.</Message>
          <Detail/>
        </Error>
        <RequestId>00000000-0000-0000-0000-000000000000</RequestId>
      </ErrorResponse>
```

I tested and latest "working" (without this error) version was 0.13.5 (but it fails with #114 :))

This version of PHP SDK works fine with "real" Amazon SQS.

**Comment by adamw** [comment]
Hm that would need debugging :) I would need some way to reproduce ... maybe you can paste some example php code? I suppose I should be able to run this somehow locally :)

**Comment by eXtreme** [comment]
sure

just require `aws/aws-sdk-php` with composer and run a simple script:

```php
<?php

require_once './vendor/autoload.php';

$sqsClient = new Aws\Sqs\SqsClient([
    'credentials' => ['key' => 'x', 'secret' => 'y'],
    'endpoint' => 'http://localhost:9324/',
    'region' => 'us-east-1',
    'version' => 'latest',
]);

$result = $sqsClient->receiveMessage([
    'QueueUrl' => 'http://localhost:9324/queue/default',
]);

print_r($result->toArray());
```

and run it from the console. 0.13.5 works. 0.13.7 fails.

You can debug the request like this:

```php
<?php

require_once './vendor/autoload.php';

$sqsClient = new Aws\Sqs\SqsClient([
    'credentials' => ['key' => 'x', 'secret' => 'y'],
    'endpoint' => 'http://localhost:9324/',
    'region' => 'us-east-1',
    'version' => 'latest',
]);

$history = new Aws\History();
$sqsClient->getHandlerList()->appendSign(Aws\Middleware::history($history));

try {
    $result = $sqsClient->receiveMessage([
        'QueueUrl' => 'http://localhost:9324/queue/morgenstern-dev-default',
    ]);

    print_r($result->toArray());
} catch (\Exception $e) {
    echo $e->getMessage();
}

var_dump($history->getLastRequest());
```

My result:

```
class GuzzleHttp\Psr7\Request#58 (7) {
  private $method =>
  string(4) "POST"
  private $requestTarget =>
  NULL
  private $uri =>
  class GuzzleHttp\Psr7\Uri#69 (7) {
    private $scheme =>
    string(4) "http"
    private $userInfo =>
    string(0) ""
    private $host =>
    string(9) "localhost"
    private $port =>
    int(9324)
    private $path =>
    string(30) "/queue/morgenstern-dev-default"
    private $query =>
    string(0) ""
    private $fragment =>
    string(0) ""
  }
  private $headers =>
  array(8) {
    'Host' =>
    array(1) {
      [0] =>
      string(14) "localhost:9324"
    }
    'Content-Length' =>
    array(1) {
      [0] =>
      string(3) "113"
    }
    'Content-Type' =>
    array(1) {
      [0] =>
      string(33) "application/x-www-form-urlencoded"
    }
    'User-Agent' =>
    array(1) {
      [0] =>
      string(18) "aws-sdk-php/3.30.2"
    }
    'aws-sdk-invocation-id' =>
    array(1) {
      [0] =>
      string(32) "74f03604efd3d9269ebe85a81b7a555c"
    }
    'aws-sdk-retry' =>
    array(1) {
      [0] =>
      string(3) "0/0"
    }
    'X-Amz-Date' =>
    array(1) {
      [0] =>
      string(16) "20170626T130908Z"
    }
    'Authorization' =>
    array(1) {
      [0] =>
      string(208) "AWS4-HMAC-SHA256 Credential=x/20170626/us-east-1/sqs/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-date, Signature=8403a4e444b7d0654a34eea3ab50b9e1f6e5b565e32f977b56aa14b2725d0146"
    }
  }
  private $headerNames =>
  array(8) {
    'host' =>
    string(4) "Host"
    'content-length' =>
    string(14) "Content-Length"
    'content-type' =>
    string(12) "Content-Type"
    'user-agent' =>
    string(10) "User-Agent"
    'aws-sdk-invocation-id' =>
    string(21) "aws-sdk-invocation-id"
    'aws-sdk-retry' =>
    string(13) "aws-sdk-retry"
    'x-amz-date' =>
    string(10) "X-Amz-Date"
    'authorization' =>
    string(13) "Authorization"
  }
  private $protocol =>
  string(3) "1.1"
  private $stream =>
  class GuzzleHttp\Psr7\Stream#67 (7) {
    private $stream =>
    resource(79) of type (stream)
    private $size =>
    int(113)
    private $seekable =>
    bool(true)
    private $readable =>
    bool(true)
    private $writable =>
    bool(true)
    private $uri =>
    string(10) "php://temp"
    private $customMetadata =>
    array(0) {
    }
  }
}
```

**Comment by eXtreme** [comment]
or instead of installing composer etc, you can just download aws.phar file from https://github.com/aws/aws-sdk-php/releases and place it beside the script above and replace `require_once './vendor/autoload.php';` with `require_once './aws.phar';`

**Comment by ankon** [comment]
I'm seeing the same with the AWS CLI and just doing a `aws --endpoint-url http://ELASTICMQ:PORT list-queues`. Debug messages:
~~~~
$ aws --debug --endpoint-url http://192.168.99.100:32000 sqs list-queues
2017-06-29 12:59:08,133 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.109 Python/3.5.3 Linux/4.10.13-200.fc25.x86_64 botocore/1.5.72
2017-06-29 12:59:08,134 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--endpoint-url', 'http://192.168.99.100:32000', 'sqs', 'list-queues']
2017-06-29 12:59:08,134 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f35a0fb7ea0>
2017-06-29 12:59:08,134 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f359f6dc400>
2017-06-29 12:59:08,135 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.5/site-packages/botocore/data/sqs/2012-11-05/service-2.json
2017-06-29 12:59:08,136 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.sqs: calling handler <function register_retries_for_service at 0x7f359fde6598>
2017-06-29 12:59:08,136 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: sqs
2017-06-29 12:59:08,137 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sqs: calling handler <function add_waiters at 0x7f35a0fdb1e0>
2017-06-29 12:59:08,140 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('queue-name-prefix', <awscli.arguments.CLIArgument object at 0x7f359e7f3940>)])
2017-06-29 12:59:08,140 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_streaming_output_arg at 0x7f35a0fcc158>
2017-06-29 12:59:08,140 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_cli_input_json at 0x7f359f6dcd90>
2017-06-29 12:59:08,140 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function unify_paging_params at 0x7f359ea3d598>
2017-06-29 12:59:08,143 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.5/site-packages/botocore/data/sqs/2012-11-05/paginators-1.json
2017-06-29 12:59:08,143 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_generate_skeleton at 0x7f359ea22b70>
2017-06-29 12:59:08,143 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f359e7f39e8>>
2017-06-29 12:59:08,143 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f359e7f3a58>>
2017-06-29 12:59:08,144 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.queue-name-prefix: calling handler <function uri_param at 0x7f359f705598>
2017-06-29 12:59:08,144 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.cli-input-json: calling handler <function uri_param at 0x7f359f705598>
2017-06-29 12:59:08,144 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.generate-cli-skeleton: calling handler <function uri_param at 0x7f359f705598>
2017-06-29 12:59:08,144 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f359e7f39e8>>
2017-06-29 12:59:08,144 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f359e7f3a58>>
2017-06-29 12:59:08,145 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-06-29 12:59:08,145 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-06-29 12:59:08,145 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-06-29 12:59:08,145 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-06-29 12:59:08,145 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.5/site-packages/botocore/data/endpoints.json
2017-06-29 12:59:08,148 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: sqs
2017-06-29 12:59:08,149 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sqs: calling handler <function add_generate_presigned_url at 0x7f35a0092950>
2017-06-29 12:59:08,153 - MainThread - botocore.endpoint - DEBUG - Setting sqs timeout as (60, 60)
2017-06-29 12:59:08,153 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sqs.ListQueues: calling handler <function generate_idempotent_uuid at 0x7f359fde1ea0>
2017-06-29 12:59:08,153 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListQueues) (verify_ssl=True) with params: {'url': 'http://192.168.99.100:32000/', 'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/1.11.109 Python/3.5.3 Linux/4.10.13-200.fc25.x86_64 botocore/1.5.72'}, 'body': {'Version': '2012-11-05', 'Action': 'ListQueues'}, 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x7f359e7bceb8>, 'has_streaming_input': False, 'auth_type': None}}
2017-06-29 12:59:08,154 - MainThread - botocore.hooks - DEBUG - Event request-created.sqs.ListQueues: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f359e7bcdd8>>
2017-06-29 12:59:08,154 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sqs.ListQueues: calling handler <function set_operation_specific_signer at 0x7f359fde1d90>
2017-06-29 12:59:08,154 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-29 12:59:08,154 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:192.168.99.100:32000
x-amz-date:20170629T105908Z

host;x-amz-date
f51ff0830b584c3138da3c5a762cdc99567f11ae790e71edd7906348cc6badab
2017-06-29 12:59:08,154 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170629T105908Z
20170629/eu-west-1/sqs/aws4_request
2de2c1b86379444be852aea6983130ade17f24d530a12aae32c64fd4770255bc
2017-06-29 12:59:08,154 - MainThread - botocore.auth - DEBUG - Signature:
74a5f29e7ef818f1742e8b8875d4a1d8c61356371a00df3b5894830d094331fb
2017-06-29 12:59:08,157 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-29 12:59:08,158 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 192.168.99.100
2017-06-29 12:59:08,166 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 837
2017-06-29 12:59:08,166 - MainThread - botocore.parsers - DEBUG - Response headers: {'server': 'akka-http/10.0.8', 'content-type': 'text/plain; charset=UTF-8', 'date': 'Thu, 29 Jun 2017 10:59:08 GMT', 'content-length': '837'}
2017-06-29 12:59:08,166 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">\n      <Error>\n        <Type>Sender</Type>\n        <Code>Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset))</Code>\n        <Message>Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset)); see the SQS docs.</Message>\n        <Detail/>\n      </Error>\n      <RequestId>00000000-0000-0000-0000-000000000000</RequestId>\n    </ErrorResponse>'
2017-06-29 12:59:08,167 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sqs.ListQueues: calling handler <botocore.retryhandler.RetryHandler object at 0x7f359e7ec780>
2017-06-29 12:59:08,167 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-06-29 12:59:08,167 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 508, in __call__
    call_parameters, parsed_globals)
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 627, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 639, in _make_client_call
    **parameters)
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset))) when calling the ListQueues operation: Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset)); see the SQS docs.
2017-06-29 12:59:08,169 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset))) when calling the ListQueues operation: Invalid request: MalformedRequestContentRejection(application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset),scala.MatchError: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset)); see the SQS docs.
~~~~

**Comment by eXtreme** [comment]
@ankon I can confirm that too

**Comment by ankon** [comment]
I bisected the error to 7569cc6c4c6d5a506382acedc4f7601e8e9e8bb4, which updated:
- akka from 2.5.1 to 2.5.3
- akka http from 10.0.6 to 10.0.8
- aws-java-sdk from 1.11.129 to 1.11.153

... and then there is http://akka.io/blog/news/2017/06/26/akka-http-10.0.9-released / https://github.com/akka/akka-http/issues/1222 appearing: updating akka http to 10.0.9 makes the error go away!

**Comment by adamw** [comment]
@ankon Great find, thanks :) releasing now
