### ISSUE TITLE
Unexpected AskTimeoutException

### ISSUE THREAD

**Issue by mkamioner** [adamw/elasticmq#50]
Hello,

I am using elasticmq-server-0.8.8

When I start the process I get a strange error. I made no changes (that I know of) that would have caused this. 

    09:36:13.382 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main
    akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://elasticmq/user/IO-HTTP#121832015]] after [10000 ms]
            at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:335) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[elasticmq-server-0.8.8.jar:0.8.8]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_65]
    :9354 failed7/2015 09:36:15.320] [elasticmq-akka.actor.default-dispatcher-6] [akka://elasticmq/user/IO-HTTP/listener-0] Bind to localhost
    [INFO] [05/17/2015 09:36:15.351] [elasticmq-akka.actor.default-dispatcher-5] [akka://elasticmq/deadLetters] Message [akka.io.Tcp$CommandFailed] from Actor[akka://elasticmq/user/IO-HTTP/listener-0#439419937] to Actor[akka://elasticmq/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
    [INFO] [05/17/2015 09:36:15.430] [elasticmq-akka.actor.default-dispatcher-5] [akka://elasticmq/system/IO-TCP/selectors/$a/0] Message [akka.dispatch.sysmsg.DeathWatchNotification] from Actor[akka://elasticmq/system/IO-TCP/selectors/$a/0#2054186458] to Actor[akka://elasticmq/system/IO-TCP/selectors/$a/0#2054186458] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

How can I stop this and what is causing this?

Thank you for your terrific solution and all your hard work!
~Mo

**Comment by adamw** [comment]
Did a previous version work? It seems the server cannot bind to the localhost/9324. What OS/java version?

**Comment by mkamioner** [comment]
Thanks for the quick response!

Previous versions worked and no longer work :-(

Java is
10:48 $ java -version
    java version "1.7.0_65"
    OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

OS is `Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)`

**Comment by mkamioner** [comment]
OK - So instead of binding to `localhost` I bind to `127.0.0.1` and it works!

Thanks for your help and sorry to bother you...

~Mo

**Comment by adamw** [comment]
np, glad it works :)
