### ISSUE TITLE
Ask timed out on [Actor[akka://elasticmq/user/IO-HTTP#940271636]] does not kill process

### ISSUE THREAD

**Issue by petercipov** [adamw/elasticmq#52]
Sometimes when I automatically execute elasticmq on starting machine I got 

```
12:05:06.080 [main] INFO org.elasticmq.server.Main$ - Starting ElasticMQ server (0.8.7) ... 12:05:59.947 [main] INFO o.e.rest.sqs.TheSQSRestServerBuilder 
- Started SQS rest server, bind address 0.0.0.0:9324, 
visible server address http://10.12.0.25:9324 12:06:09.865 
[main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://elasticmq/user/IO-HTTP#940271636]] after [10000 ms] 
at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[elasticmq-server-0.8.7.jar:0.8.7] 
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45] 
```

The java process is running, but sqs service is unresponsive.

I would expect two possible behaviours: 
* elasticmq retries sqs until success, 
* or elasticmq kills itself so I can restart it by script.

When machine is not under pressure, (all other services have already started), elasticmq will start properly. Problematic is concurrent start with other services.

**Comment by adamw** [comment]
Duplica of #61
